movie_title = "Avengers Endgame"  
two_dimension_or_three_dimension = "3D"                   
ticket_price = 18.00              
number_of_tickets = 3             
is_weekend = True                 
has_student_discount = False  
popcorn_combo = "Large"            
total_price = 54.00              
customer_age = 25                
member_id = "M1234"