name: Lab 07 Tests

on:
  push:
    paths:
      - 'labs/lab07/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: labs/lab07

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@
        with:
          python-version: '3.x'

      # Check for exercise files
      - name: Verify exercise1.py exists
        run: test -f exercise1.py

      - name: Verify exercise2.py exists
        run: test -f exercise2/exercise2.py

      - name: Verify exercise3.py exists
        run: test -f exercise3/exercise3.py

      - name: Verify exercise4.py exists
        run: test -f exercise4/exercise4.py

      - name: Verify exercise5.py exists
        run: test -f exercise5/exercise5.py